### ISSUE TITLE
The extension does not work on Wayland session

### ISSUE THREAD

**Issue by crackerizer** [luispabon/maximus-gnome-shell#19]
This extension does not work on Wayland session with 'Error loading extension' message on the tweak tool. To reproduce,

1. Install gnome-session-wayland
2. Restart your computer
3. Login as Wayland session.

**Comment by simonbcn** [comment]
To me work on Arch Linux 64 with Gnome Shell 3.22.2

**Comment by in0ni** [comment]
The extension works for me on arch using gnome-shell v3.22.2 and wayland, though what I am noticing is that it only works on windows for _some_ applications. For example, it works with Firefox, but not with Terminal. When I switch to using X everything works just fine.

I assume this is due to the use of X related code (like `xprop`), and perhaps Firefox is running as an X client in Wayland (`xorg-server-wayland`?).

**Comment by luispabon** [comment]
Quite possibly, yes. All the code around working out window properties is rather X specific and I have little knowledge or time to support Wayland at the moment. Help / PRs appreciated.

**Comment by osminogin** [comment]
Also got this trouble. This and other same popular extensions didn't work on latest Ubuntu 20.04 LTS with standart wayland session (default after fresh install). Required `xprop` is installed.

**Comment by luispabon** [comment]
Hey there. This extension is now abandoned I'm afraid for a couple of years now.

I would recommend to you the [Unite](https://extensions.gnome.org/extension/1287/unite/) extension, which among other things does the same thing as maximus, but works much better (pretty close to what Unity did with the top panel actually).
